version: "3.6"

networks:
  previewer:

services:
  go_build:
    container_name: ipreviewer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    environment:
      - LRU_CACHE_CAPACITY=${LRU_CACHE_CAPACITY}
    networks:
      - previewer

  nginx:
    image: nginx:1.21.4
    ports:
      - "80:80"
    volumes:
      - ./build/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - go_build
    depends_on:
      - go_build
    networks:
      - previewer
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 2s
      retries: 3
      start_period: 40s